### ISSUE TITLE
 Branch Protection Rule

### ISSUE THREAD

**Issue by mohammadrezadehbashi** [codewithmohsen/m2commerce_front#5]
When does this error occur during push in Git ?

git push origin main
Enumerating objects: 874, done.
Counting objects: 100% (870/870), done.
Delta compression using up to 8 threads
Compressing objects: 100% (821/821), done.
Writing objects: 100% (826/826), 49.19 MiB | 103.00 KiB/s, done.
Total 826 (delta 732), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (732/732), completed with 10 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Changes must be made through a pull request.
To https://github.com/codewithmohen/m2commerce_front.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/codewithmohen/m2commerce_front.git'

**Comment by mohammadrezadehbashi** [comment]
This error occurs when you're attempting to push changes to a branch on GitHub that has branch protection rules enabled. These rules are set to enforce certain checks or restrictions on the branch, such as requiring pull requests for changes to be merged into the branch.

In this case, the error message GH006: Protected branch update failed for refs/heads/main indicates that the branch you're trying to push changes to (main) has branch protection rules enabled on GitHub. The specific rule in place requires changes to be made through a pull request rather than directly pushing commits to the branch.

To resolve this error, you typically have a few options:

1.**Create a Pull Request**: If branch protection rules require changes to go through a pull request, create a pull request on GitHub from your branch with the changes into the main branch. Then, the changes can be reviewed and merged through the pull request.

2.**Disable Branch Protection (if permitted)**: If you have the necessary permissions, you can temporarily disable branch protection rules for the main branch on GitHub. After pushing your changes, you can re-enable the protection.

3.**Seek Assistance**: If you don't have the permissions to disable branch protection or if there are specific guidelines in place, reach out to the repository administrators or maintainers for guidance on how to proceed with your changes.

It's essential to follow the repository's guidelines and rules set for branch protection to maintain code quality and ensure proper collaboration within the team.

**Comment by codewithmohen** [comment]
yes now protection accepted ur merge by me, tnx for ur issue :)

**Comment by codewithmohsen** [comment]
yes now protection accepted ur merge by me, tnx for ur issue :)

**Comment by mohammadrezadehbashi** [comment]
tnx bro
